'use client'

import { useMemo, useState } from 'react'
import { Bookmark, BookmarkCheck, CalendarDays, ExternalLink, Newspaper, Search, Share2, TrendingDown, TrendingUp, WalletCards } from 'lucide-react'
import { toast } from 'sonner'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'

const categories = ['All', 'General Finance & Economy', 'Tax & Policy Updates', 'Investment & Market News', 'Personal Finance Tips', 'Banking & Interest Rates', 'Cryptocurrency & Digital Assets', 'Real Estate Market', 'Government Schemes & Benefits', 'Transport', 'Health', 'Subscriptions', 'Food']
const articles = [
  { id: 1, headline: 'Petrol prices rise by ₹4 per litre as global crude moves higher', source: 'Moneycontrol', hours: 2, category: 'Transport', priority: 'critical', summary: 'Fuel prices have reached a yearly high after supply concerns pushed crude oil higher. Commuters and delivery businesses may see costs change this month.', relevance: 'Relevant to your Transport spending', url: 'https://www.moneycontrol.com/', icon: '⛽', impact: { type: 'petrol', rate: 4 } },
  { id: 2, headline: 'RBI keeps repo rate unchanged at 6.5%', source: 'Economic Times', hours: 3, category: 'Banking & Interest Rates', priority: 'important', summary: 'The central bank maintained its policy rate while watching inflation and growth. Floating-rate borrowers can expect stability for now.', relevance: 'Relevant to your loans and savings', url: 'https://economictimes.indiatimes.com/', icon: '🏦', impact: { type: 'loan', rate: 0 } },
  { id: 3, headline: 'New tax-saving scheme expands ELSS deductions', source: 'PIB', hours: 5, category: 'Tax & Policy Updates', priority: 'critical', summary: 'The proposed scheme adds flexibility to tax-saving investments while retaining the Section 80C limit. Check eligibility before investing.', relevance: 'Relevant to your tax planning', url: 'https://pib.gov.in/', icon: '📋', impact: { type: 'tax', rate: 45000 } },
  { id: 4, headline: 'Sensex rallies as foreign investors return to Indian equities', source: 'Mint', hours: 7, category: 'Investment & Market News', priority: 'informational', summary: 'Indian benchmarks gained as foreign portfolio flows improved. Short-term market movements should not replace a long-term plan.', relevance: 'Relevant to your Investment transactions', url: 'https://www.livemint.com/', icon: '📈', impact: { type: 'investment', rate: 1.2 } },
  { id: 5, headline: 'Health insurance premiums may rise 8-10% next year', source: 'Business Standard', hours: 9, category: 'Health', priority: 'important', summary: 'Insurers are reviewing premiums in response to medical inflation and claim ratios. Review renewal dates and coverage before the next cycle.', relevance: 'Relevant to your Health spending', url: 'https://www.business-standard.com/', icon: '🏥', impact: { type: 'health', rate: 0.09 } },
  { id: 6, headline: 'Streaming platforms announce new plans and bundled launches', source: 'BusinessLine', hours: 12, category: 'Subscriptions', priority: 'informational', summary: 'Several platforms are changing plan tiers and adding bundled services. Compare annual and monthly pricing before renewing.', relevance: 'Relevant to your recurring subscriptions', url: 'https://www.thehindubusinessline.com/', icon: '▶', impact: { type: 'subscription', rate: 100 } },
  { id: 7, headline: 'Food inflation eases as vegetable supply improves', source: 'Reuters', hours: 16, category: 'Food', priority: 'informational', summary: 'Improved arrivals are easing prices for several staples, although restaurant prices remain sticky in urban markets.', relevance: 'Relevant to your Food spending', url: 'https://www.reuters.com/world/india/', icon: '🍲', impact: { type: 'food', rate: -0.03 } },
  { id: 8, headline: 'Government launches an updated home-buyer subsidy portal', source: 'NDTV Profit', hours: 20, category: 'Government Schemes & Benefits', priority: 'important', summary: 'Eligible first-time buyers can check new benefit thresholds and application status online through the updated portal.', relevance: 'Useful for your long-term goals', url: 'https://www.ndtvprofit.com/', icon: '🏠', impact: { type: 'home', rate: 150000 } },
]
const market = [['Sensex', '82,450', '+1.20%', true], ['Nifty 50', '25,180', '+0.80%', true], ['Gold / 10g', '₹72,500', '-0.50%', false], ['USD / INR', '83.45', '+0.20%', true], ['Crude / barrel', '$87.50', '+3.20%', false], ['Repo rate', '6.50%', 'No change', true]]
function money(value) { return `₹${Math.round(Math.abs(value || 0)).toLocaleString('en-IN')}` }
function spendingByCategory(transactions) { return (transactions || []).filter(t => t.type !== 'income').reduce((totals, t) => ({ ...totals, [t.category || 'Other']: (totals[t.category || 'Other'] || 0) + Number(t.amount || 0) }), {}) }
function impact(article, totals) {
  const monthly = (totals[article.category] || 0) / 3
  const type = article.impact.type
  if (type === 'petrol') return ['Estimated fuel impact', money(monthly * 0.65 * article.impact.rate / 100), `Based on ${money(monthly)} average monthly Transport spending and a 65% fuel share.`]
  if (type === 'health') return ['Estimated annual premium impact', money(monthly * 12 * article.impact.rate), 'Planning estimate; your insurer renewal quote is the source of truth.']
  if (type === 'food') return ['Potential monthly saving', money(monthly * Math.abs(article.impact.rate)), 'Estimate if lower food inflation reaches your usual basket.']
  if (type === 'subscription') return ['Plan change to watch', `+${money(article.impact.rate)}/month`, 'Compare recurring services before the next renewal date.']
  if (type === 'tax') return ['Potential tax benefit', money(article.impact.rate), 'Illustrative maximum; verify regime and eligibility.']
  if (type === 'investment') return ['Market context', `${article.impact.rate}% move`, 'A market signal, not a forecast of portfolio return.']
  if (type === 'home') return ['Potential scheme benefit', `Up to ${money(article.impact.rate)}`, 'Income limits and property criteria apply.']
  return ['Personal impact', 'Stable', 'Review loan and savings products for current terms.']
}
function priorityClass(priority) { return priority === 'critical' ? 'bg-red-100 text-red-700 border-red-200' : priority === 'important' ? 'bg-amber-100 text-amber-700 border-amber-200' : 'bg-emerald-100 text-emerald-700 border-emerald-200' }

export default function NewsAndMarketDashboard({ transactions = [], analysis = {} }) {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('All')
  const [saved, setSaved] = useState([])
  const totals = useMemo(() => ({ ...spendingByCategory(transactions), ...(analysis?.spending?.categoryBreakdown || []).reduce((result, item) => ({ ...result, [item.category]: Number(item.amount || item.total || 0) }), {}) }), [transactions, analysis])
  const watched = Object.keys(totals).filter(item => totals[item] > 0)
  const filtered = articles.filter(article => (category === 'All' || article.category === category || category === 'General Finance & Economy' && article.category === 'Banking & Interest Rates') && (!query.trim() || `${article.headline} ${article.summary} ${article.category}`.toLowerCase().includes(query.toLowerCase())))
  const save = article => { setSaved(current => current.includes(article.id) ? current.filter(id => id !== article.id) : [...current, article.id]); toast.success(saved.includes(article.id) ? 'Removed from saved articles' : 'Article saved for later') }
  const share = async article => { if (navigator.share) await navigator.share({ title: 'FinWise Financial News', text: article.headline, url: article.url }).catch(() => {}); else { await navigator.clipboard?.writeText(article.url); toast.success('Article link copied') } }
  return <div className="space-y-5">
    <div className="rounded-2xl bg-slate-950 p-5 text-white shadow-xl"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-cyan-300"><Newspaper className="h-4 w-4" /> FinWise intelligence</div><h2 className="text-2xl font-bold tracking-tight">Financial News & Market Pulse</h2><p className="mt-1 max-w-2xl text-sm text-slate-300">News that explains what is moving your money, filtered around your spending and goals.</p></div><Badge className="border border-cyan-400/30 bg-cyan-400/10 text-cyan-200">{watched.length ? `${watched.length} personal signals` : 'Personalized feed'}</Badge></div>{watched.length > 0 && <div className="mt-4 flex flex-wrap gap-2 text-xs text-slate-300"><span className="font-semibold text-white">Watching your:</span>{watched.slice(0, 5).map(item => <span key={item} className="rounded-full bg-white/10 px-2.5 py-1">{item} · {money(totals[item])}</span>)}</div>}</div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">{market.map(([name, value, change, positive]) => <Card key={name} className="border-0 bg-white/90 shadow-sm"><CardContent className="p-3"><div className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{name}</div><div className="mt-1 text-lg font-bold text-slate-800">{value}</div><div className={`mt-1 flex items-center gap-1 text-xs font-semibold ${positive ? 'text-emerald-600' : 'text-rose-600'}`}>{positive ? <TrendingUp className="h-3 w-3" /> : <TrendingDown className="h-3 w-3" />}{change}</div></CardContent></Card>)}</div>
    <Card className="border-0 shadow-md"><CardContent className="space-y-3 p-4"><div className="flex items-center gap-2"><Search className="h-4 w-4 text-slate-400" /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search financial news..." /></div><div className="flex gap-2 overflow-x-auto pb-1">{categories.map(item => <Button key={item} size="sm" variant={category === item ? 'default' : 'outline'} onClick={() => setCategory(item)} className="shrink-0">{item}</Button>)}</div></CardContent></Card>
    <div className="grid gap-4 lg:grid-cols-2">{filtered.map(article => { const [title, value, detail] = impact(article, totals); const isSaved = saved.includes(article.id); return <Card key={article.id} className="overflow-hidden border-0 bg-white shadow-md transition-shadow hover:shadow-lg"><CardContent className="p-5"><div className="flex gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-2xl">{article.icon}</div><div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap items-center gap-2"><Badge variant="outline" className="border-slate-200 text-slate-600">{article.category}</Badge><Badge variant="outline" className={priorityClass(article.priority)}>{article.priority}</Badge></div><a href={article.url} target="_blank" rel="noreferrer" className="text-base font-bold leading-snug text-slate-900 hover:text-cyan-700">{article.headline}</a><div className="mt-1 text-xs text-slate-500">{article.source} • {article.hours} hours ago</div></div></div><p className="mt-4 text-sm leading-relaxed text-slate-600">{article.summary}</p><div className="mt-3 rounded-lg border border-cyan-100 bg-cyan-50 px-3 py-2 text-xs font-semibold text-cyan-800">📍 {article.relevance}</div><div className="mt-3 rounded-xl border border-slate-100 bg-slate-50 p-3"><div className="flex items-center justify-between"><div><div className="text-xs font-bold uppercase tracking-wide text-slate-500">Smart financial impact</div><div className="mt-1 font-bold text-slate-900">{title}: <span className="text-cyan-700">{value}</span></div></div><WalletCards className="h-5 w-5 text-cyan-600" /></div><p className="mt-1 text-xs text-slate-500">{detail}</p></div><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" onClick={() => window.open(article.url, '_blank', 'noopener,noreferrer')}><ExternalLink className="mr-2 h-3.5 w-3.5" /> Read more</Button><Button size="sm" variant="outline" onClick={() => save(article)}>{isSaved ? <BookmarkCheck className="mr-2 h-3.5 w-3.5" /> : <Bookmark className="mr-2 h-3.5 w-3.5" />} {isSaved ? 'Saved' : 'Save'}</Button><Button size="sm" variant="ghost" onClick={() => share(article)}><Share2 className="mr-2 h-3.5 w-3.5" /> Share</Button></div></CardContent></Card> })}</div>
    {filtered.length === 0 && <Card><CardContent className="p-10 text-center text-sm text-slate-500">No articles match this view. <Button variant="link" onClick={() => { setCategory('All'); setQuery('') }}>Clear filters</Button></CardContent></Card>}
    <Card className="border-0 bg-amber-50 shadow-sm"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base text-amber-950"><CalendarDays className="h-4 w-4" /> Financial moments to watch</CardTitle></CardHeader><CardContent className="grid gap-3 text-sm text-amber-900 md:grid-cols-3"><div><strong>Oct 5</strong><p className="text-xs">Credit card bill due</p></div><div><strong>Dec 15</strong><p className="text-xs">Q3 advance tax payment</p></div><div><strong>Jul 31</strong><p className="text-xs">Income tax return deadline</p></div></CardContent></Card>
  </div>
}
